spring:
    profiles: dev
    jpa.hibernate.ddl-auto: validate

server.port: 8080

logging:
    level:
        org.jboss.resteasy.springmvc.ResteasyHandlerMapping: ERROR
        org.meruvian.yama: DEBUG

rest:
    login_form: /index.html

# database
db:
    url: jdbc:mysql://localhost:3306/yama2news
    driver: com.mysql.jdbc.Driver
    datasource: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    username: root
    password: root
    max_pool_size: 100
    test_query: SELECT 1
    run_migration: true
    
# upload
upload:
    path:
        base: /tmp/yama
        profile_pic: /profile_pic

# default
default:
    role: USER
    site: DEFAULT
    profile_pic:
        path: /images/default_profile.gif
        content_type: image/gif

# social
social:
    mervid:
        active: true
        appId: 2181e855-33ce-4345-acd2-9111e6d3bae9
        appSecret: 4/gdliEbLsml2IO4XC51DfDjlLSPZGcgXHFnMFHv328aSahA4/x75cSk//Hm5es7
        redirectUri: http://news1.yama2.meruvian.org/login/social/mervid/callback
        scope: read write
        state: 6234
    facebook:
        active: true
        appId: 1582311285372107
        appSecret: fe7655ddd626ca55a987423230441254
        redirectUri: http://news1.yama2.meruvian.org/login/social/facebook/callback
        scope: email,public_profile,user_friends
        state: 6234

    google:
        active: true
        appId: 474621335265-3bit11krp5kf8bes4eumrqabinhnuemh.apps.googleusercontent.com
        appSecret: VKerS5V_f4bXBbbomb3Bdcod
        redirectUri: http://news1.yama2.meruvian.org/login/social/google/callback
        scope: https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.me https://www.googleapis.com/auth/userinfo.email
        state: 6234

# email
email:
    host: localhost
    port: 25
    username: 
    password: 
    from_email: yama@localhost
    from_alias: Yama
    ssl: false
    tls: false

# recaptcha
recaptcha:
    active: true
    public_key: 6LdoBdESAAAAAHXfBTxpdn0gdlo3Ov3oLaOf4Jeh
    private_key: 6LdoBdESAAAAAKF_QC5MSRVwLbXvozXLjljUFEsG
    include_noscript: false
